### PR TITLE
Framework

### PR DESCRIPTION
**Pull request by premsvmm**

### CODE REVIEW

**Comment by ankuriitk** [comment]
hey @premsvmm : is this ready for review?

**Comment by ankuriitk** [comment]
Also Please add @lokeshdevnani and @Rohanhacker to the code review. They are the frontend experts at Clarisights.

**Comment by premsvmm** [comment]
@ankuriitk I completed the first question
For the second question, I created the web service for POST and GET. Need to automate those rest api's. 
I think if you review the code for the first question, i will merge it and create a seperate PR for the second question. Please let me know.

**Comment by ankuriitk** [comment]
Please create two different PRs one for each problem. Will review in one
shot.

**Pull request merged**
